version: '3.8'

services:
  swiftsearch_db:
    image: mysql:5.7
    container_name: swiftsearch_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "10301:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - swiftsearch

  swiftsearch_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: swiftsearch_phpmyadmin
    environment:
      PMA_HOST: swiftsearch_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "10302:80"
    depends_on:
      - swiftsearch_db
    networks:
      - swiftsearch

networks:
  swiftsearch:

volumes:
  mysql_data:
