name: Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 18.16.0

      - name: Install dependencies
        working-directory: app   # Specify the working directory as 'app'
        run: npm install

      - name: Build the Application
        working-directory: app   # Specify the working directory as 'app'
        run: npm run build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: swiftsearch
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-1'
          SOURCE_DIR: 'app/dist'  # Specify the source directory as 'app/dist'
