name: Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'app/**' # Specify the path to the app folder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 10.14.1
        uses: actions/setup-node@v1
        with:
          node-version: 10.14.1

      - name: Install dependencies
        run: npm install

      - name: Build the Application
        run: npm run build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: swiftsearch-app
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-1'
          SOURCE_DIR: 'dist'
